# Generated by Django 5.2.6 on 2025-09-13 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_epi', '0002_remove_epi_ativo_remove_epi_estoque_atual_and_more'),
        ('app_usuarios', '0003_alter_colaborador_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('observacao_devolucao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=12)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='app_usuarios.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='app_epi.epi')),
            ],
        ),
    ]
