# Generated by Django 5.2.4 on 2025-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=12),
        ),
    ]
