# Generated by Django 5.2.4 on 2025-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimos', '0002_alter_emprestimo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='condicao_emprestimo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
