# Generated by Django 5.2.6 on 2025-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
