# Generated by Django 5.2.6 on 2025-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_colaborador_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
    ]
