# Generated by Django 5.2.4 on 2025-09-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=20)),
                ('ca', models.CharField(max_length=20)),
                ('validade_ca', models.DateField()),
                ('tamanho', models.CharField(max_length=20)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('vida_util_meses', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
