# Generated by Django 5.2.6 on 2025-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_epi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='estoque_minimo',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='validade_ca',
        ),
        migrations.AddField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epi',
            name='ca',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='vida_util_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
