# Generated by Django 5.2.4 on 2025-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_epi', '0002_remove_epi_ativo_remove_epi_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='ca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
